#! /usr/bin/perl

##	This script walks your apache configuration beginning from 
##	the file defined in $conf. It follows all includes and prints
##	to stdout everything that is neither comment nor include. It's 
##	aimed at piping to other utilities - grepping for repeated 
##	configuration, for example.


use strict;
use 5.010;

my $conf = "/etc/apache2/apache2.conf";
my $fhcount = 1;

&walk_file($conf);


sub walk_file() {
	my $filename = $_[0];
	my $fh = "fh".$fhcount;
	$fhcount++;
	open (my $fh, "< $filename") or die ("Error opening file: $filename");
	while(<$fh>){
		given ($_){
			when ((/^#/) || (/^$/)){
				print "";
			}
			when (/^Include/){
				&include($_);
			}
			default{
				print;
			}
		}
	}
	close($fh)
}	

sub include() {
	my @line = split(/\s/, $_);
	my $path = pop(@line);
	chomp $path;
	if(($path =~ /\*/) || ($path =~ /\/$/)){
		$path =~ s/\/$/\/\*/;
		foreach(glob($path)){
			&walk_file($_);
		}
	}else{
		if(-f $path && -s $path){
			&walk_file($path);
		}elsif(-d $path){
			&walk_dir($path);
		}else{
			if (-s $path){
				last;
			}
		}
	}
}


sub walk_dir() {
	my $dirname = shift;
	opendir(DIR, $dirname);
	foreach(sort(readdir(DIR))){
		&walk_file($_) if ($_ !~ /^./);
	}
}
