#! /usr/bin/perl

use strict;

## Chance in 1000 that Jon should be kicked:
my $chance = 100;

## Minimum time to wait between kicks, in minutes:
my $betweenKicks = 20;

## Command to run to kick Jon
my $kickJon = "echo \"1\"";

## Where to point stderr and stdout
my $errors = "/home/avi/bin/test/kickjond.err";
my $out = "/home/avi/bin/test/kickjond.out";





use POSIX qw(setsid);

&daemonise;

my $betweenKicks = $betweenKicks * 60;
my $lastkick = 0;


while(1) {
	if ((time - $lastkick) > $betweenKicks){
	
		my $kick = int(rand(1000));

		if ($kick > $chance){
			`$kickJon`;
			my $lastkick = time();
		}
	}
	sleep(3);
}

sub daemonise {
	chdir '/' or die "error chdiring to / : $!";
	open (STDIN, "/dev/null") or die "Error reading from /dev/null : $!";
	open (STDOUT, ">>",  "$out") or die "Error attaching STDOUT to $out : $!"; 
	open (STDERR, ">>", "$errors") or die "Error attaching STDERR to $errors : $!";
	defined(my $pid = fork ) or die "Error forking : $!";
	exit if $pid;
	setsid or die "Error starting new session : $!";
	umask 0;
}
