#! /usr/bin/perl

## Chance in 100 that Jon should be kicked:
my $chance = 10;

## Minimum time to wait between kicks, in minutes:
my $betweenKicks = 20;

## Command to run to kick Jon
my $kickJon = 'screen -x minecraft -X stuff "`printf \'kick n1md4 \r\'`"';

## Where to point stderr and stdout
my $errors = "/dev/null";
my $out = "/dev/null";

use strict;
use POSIX qw(setsid);

my $betweenKicks = $betweenKicks * 60;
my $lastKick = 0;
my $chance = $chance * 10;

&daemonise;
while(1) {
	if ((time - $lastKick) > $betweenKicks){
		if (int(rand(1000)) <= $chance){
			`$kickJon`;
			$lastKick = time();
		}
	}
	sleep(60);
}

sub daemonise {
	chdir '/' or die "error chdiring to / : $!";
	open (STDIN, "<", "/dev/null") or die "Error reading from /dev/null : $!";
	open (STDOUT, ">>",  "$out") or die "Error attaching STDOUT to $out : $!"; 
	open (STDERR, ">>", "$errors") or die "Error attaching STDERR to $errors : $!";
	defined(my $pid = fork ) or die "Error forking : $!";
	exit if $pid;
	setsid or die "Error starting new session : $!";
	umask 0;
}
