#! /usr/bin/perl

# Handy script to make commonly-repeated ftp uploads
# quicker and more painless.

use strict;

use Net::FTP;

#my $config_file = "$ENV{HOME}/.ptfe";
my $config_file = "./.ptfe";
my %config;
open (F, "<$config_file");
while(<>){
	chomp;
	my($key,$value)=(split(/=/, $_))[0,1];

	$config{$key}=$value;
}
close F;


print $config{username};
exit 0;

## Credentials:
my $hostname="localhost";	
my $username="username";	
my $password="Password";


# Once we're connected, we'll cd to this dir:
my $cwd="www";
# And upload this file (the first argument):
my $file = $ARGV[0];

##

my $ftp;
$ftp = Net::FTP->new("$hostname", Debug => 0)
  or die("Error connecting: ", $ftp->message);

$ftp->login($username, $password)
  or die("Error logging in: ", $ftp->message);

if ($cwd){
	$ftp->cwd($cwd)
	  or die("cwd (to $cwd) failed: ", $ftp->message);
}

$ftp->put($file)
  or die("Put failed: ", $ftp->message);
